<?xml version="1.0"?>
<package format="3">
  <name>path_manager</name>
  <version>0.0.1</version>
  <description>Path management package for planning and optimizing trajectories</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>Eigen3</depend>
  <depend>path_optimizer</depend>
  <depend>path_planner</depend>
  <depend>geometry_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>mmp_mission_msgs</depend>
  <depend>mmp_traj_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>grid_map_msgs</depend>
  <depend>yaml-cpp</depend>
  <depend>ament_index_cpp</depend>

  <exec_depend>nav_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>